#!/usr/bin/env python3
"""
Visual Test Analyzer for Canicross
Analyzes screenshots generated by VisualTester and reports issues.
"""

import os
import sys
from pathlib import Path
from PIL import Image
import colorsys

def analyze_image(image_path):
    """Analyze a screenshot for common visual issues."""
    issues = []
    img = Image.open(image_path)
    width, height = img.size
    pixels = img.load()
    
    # Check 1: Is the image mostly blank/solid color? (rendering failed)
    unique_colors = set()
    sample_pixels = []
    for y in range(0, height, 10):
        for x in range(0, width, 10):
            sample_pixels.append(pixels[x, y])
            unique_colors.add(pixels[x, y])
    
    if len(unique_colors) < 50:
        issues.append("Imagem muito uniforme - possivel erro de renderizacao")
    
    # Check 2: Is the dog visible? (look for brown/orange pixels in expected region)
    # Expected dog position is usually in center-right area
    dog_region = img.crop((width * 0.4, height * 0.3, width * 0.7, height * 0.8))
    dog_pixels = list(dog_region.getdata())
    brownish = sum(1 for p in dog_pixels if p[0] > 100 and p[1] > 50 and p[1] < 200 and p[2] < 100)
    if brownish < 100:
        issues.append("Cachorro pode nao estar visivel ou ter cor incorreta")
    
    # Check 3: Is ground visible at bottom? (green/brown pixels)
    bottom_region = img.crop((0, height * 0.7, width, height))
    bottom_pixels = list(bottom_region.getdata())
    ground_pixels = sum(1 for p in bottom_pixels if p[1] > 50 and p[1] > p[2])
    if ground_pixels < len(bottom_pixels) * 0.1:
        issues.append("Chao pode estar faltando ou ter cor incorreta")
    
    # Check 4: Brightness check (too dark or too bright)
    avg_brightness = sum(sum(p[:3]) / 3 for p in sample_pixels) / len(sample_pixels)
    if avg_brightness < 30:
        issues.append("Imagem muito escura - problema de iluminacao")
    elif avg_brightness > 240:
        issues.append("Imagem muito clara - possivel overexposure")
    
    # Check 5: Check for blue tether line
    blue_pixels = sum(1 for p in dog_pixels if p[2] > 150 and p[2] > p[0] and p[2] > p[1])
    if blue_pixels < 10 and "CloseUp" not in str(image_path):
        issues.append("Guia elastica pode nao estar visivel (poucos pixels azuis)")
    
    return issues


def main():
    base_dir = Path("/mnt/c/Users/alexa/Projetos/cani-game/TestResults/Visual")
    
    if not base_dir.exists():
        print(f"Directory not found: {base_dir}")
        print("Run Visual Tests in Unity first: Canicross > Run Visual Tests")
        sys.exit(1)
    
    images = sorted(base_dir.glob("*.png"))
    
    if not images:
        print("No PNG images found in Visual test directory.")
        sys.exit(1)
    
    print("=" * 60)
    print("CANICROSS - ANALISE DE TESTES VISUAIS")
    print("=" * 60)
    
    all_issues = []
    
    for img_path in images:
        print(f"\nAnalisando: {img_path.name}")
        issues = analyze_image(img_path)
        
        if issues:
            print("  PROBLEMAS ENCONTRADOS:")
            for issue in issues:
                print(f"    - {issue}")
                all_issues.append(f"{img_path.name}: {issue}")
        else:
            print("  OK - Sem problemas detectados")
    
    print("\n" + "=" * 60)
    print("RESUMO")
    print("=" * 60)
    
    if all_issues:
        print(f"Total de problemas: {len(all_issues)}")
        print("\nLista completa:")
        for issue in all_issues:
            print(f"  - {issue}")
        print("\nRECOMENDACAO: Corrija os problemas acima e rode os testes novamente.")
        sys.exit(1)
    else:
        print("Todos os testes passaram! Nenhum problema visual detectado.")
        sys.exit(0)


if __name__ == "__main__":
    main()
